name: RDP Publico con Localtonet

on:
  workflow_dispatch:

jobs:
  secure-rdp:
    runs-on: windows-latest
    timeout-minutes: 360
    steps:
      - name: Configurar Escritorio Remoto
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "SecurityLayer" -Value 0 -Force
          netsh advfirewall firewall delete rule name="RDP"
          netsh advfirewall firewall add rule name="RDP" dir=in action=allow protocol=TCP localport=3389
          Restart-Service -Name TermService -Force

      - name: Crear Usuario
        run: |
          $username = "YamzzOfficial"
          $password = "YamzzOffical@123"
          $securePass = ConvertTo-SecureString $password -AsPlainText -Force
          New-LocalUser -Name $username -Password $securePass -AccountNeverExpires
          Add-LocalGroupMember -Group "Administrators" -Member $username
          Add-LocalGroupMember -Group "Remote Desktop Users" -Member $username

      - name: Instalar y Ejecutar Localtonet
        run: |
          Write-Host "Descargando Localtonet..."
          Invoke-WebRequest -Uri "https://localtonet.com/download/localtonet-windows-amd64.zip" -OutFile "localtonet.zip"
          Expand-Archive localtonet.zip -DestinationPath .
          
          Write-Host "* === DATOS DE ACCESO RDP === *"
          Write-Host "Revisa tu panel web de Localtonet (https://localtonet.com/dashboard) para ver la IP y el puerto asignados."
          Write-Host "Username: YamzzOfficial"
          Write-Host "Password: YamzzOffical@123"
          Write-Host "********"
          
          # Iniciar Localtonet de forma visible. Esto mantiene el servidor de GitHub Actions corriendo.
          .\localtonet.exe -t ${{ secrets.LOCALTONET_AUTH_TOKEN }}
